version: 2
updates:
# Default Branch
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - RandomByte
  - matz3
  versioning-strategy: increase
# v2 Branch
- package-ecosystem: "github-actions"
  target-branch: v2
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: npm
  target-branch: v2
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "10:00"
    timezone: Etc/UCT
  reviewers:
  - RandomByte
  - matz3
  versioning-strategy: increase
